app/game/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, RadioField
from wtforms.validators import DataRequired
from ..games import Room


class GameForm(FlaskForm):
    action = StringField('Action', validators=[DataRequired()])
    submit = SubmitField('Submit')


class GameQuizForm(FlaskForm):
    action = RadioField('Action')
    submit = SubmitField('Submit')

    def __init__(self, room, *args, **kwargs):
        super(GameQuizForm, self).__init__(*args, **kwargs)
        self.action.choices = [(key, key) for key in room.paths.keys()]
        self.room = room

app/game/__init__.py
from flask import Blueprint

game = Blueprint('game', __name__)

from . import forms, routes  # noqa

app/game/routes.py
from flask import redirect, url_for, request, render_template
from flask import current_app, session, flash
from flask_login import login_required, current_user
from . import game
from .. import db
from ..models import Ranking
from .forms import GameForm, GameQuizForm
from ..games import available_games
import pickle


@game.route("/<name>", methods=['GET', 'POST'])
@login_required
def play(name):
    if not available_games[name]:
        session.pop('game')
        return abort(404)

    if not session.get('game'):
        game = available_games[name]()
    else:
        game = pickle.loads(session.get('game'))
        if (game.name != name
                or request.referrer is None
                or (request.referrer and 'game' not in request.referrer)
                or game.is_game_over()):
            game = available_games[name]()

    current_room = game.current_room
    if current_room.is_quiz():
        form = GameQuizForm(current_room)
    else:
        form = GameForm()

    if form.validate_on_submit():
        action = form.action.data
        new_room, msg = game.go(action)
        if msg is not None and msg != '':
            # wrong answer
            flash(msg, 'error')
            if not game.current_room.is_quiz():
                form.action.data = ''

        if game.is_game_over():
            # game_over
            r = Ranking(game=game.name, score=game.calculated_score(),
                        user=current_user._get_current_object())
            db.session.add(r)
            db.session.commit()
            session['game'] = pickle.dumps(game)
            return redirect(url_for(".gameover"))

        # next room
        if new_room != current_room:
            if not current_room.is_quiz():
                flash("You passed!", "success")
        else:
            game.trials += 1  # same room, new trial
        session['game'] = pickle.dumps(game)
        return redirect(url_for('.play', name=game.name))

    session['game'] = pickle.dumps(game)
    return render_template(f"/game/game.html", form=form, game=game)


@game.route("/gameover", methods=['GET'])
@login_required
def gameover():
    if session.get('game'):
        game = pickle.loads(session.get('game'))
        if game.is_game_over():
            session.pop('game')
            return render_template("/game/gameover.html", game=game)
    return redirect(url_for('main.home'))

app/templates/game/_gameroom.html
<div class="game-room">
    <h1>{{ game.show_name }}</h1>
    <p class="game-description"><i>{{ game.description }}</i></p>

    <h3 style="margin-top: 40px;">{{ game.current_room.name }}</h3>

    <p class="room-description">
        {{ game.current_room.description|safe }}
    </p>

    {% if game.current_room.img_file %}
    <img class="room-image" src="{{ url_for('static', filename='/img/{}/{}'.format(game.name, game.current_room.img_file)) }}">
    {% endif %}

</div>

app/templates/game/game.html
{% extends "layout.html" %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='/css/game.css') }}">
{% endblock %}

{% block content %}

<div class="game-container">
    {% include 'game/_gameroom.html' %}

    <form method="POST"> 
        {{ form.hidden_tag() }}
        {% if game.current_room.is_quiz() %}
            {% for subfield in form.action %}
                <div class="form-group-quiz">
                    {{ subfield }}{{ subfield.label }}
                </div>
            {% endfor %}
            {{ form.submit(class_='submit') }}
        {% else %}
            <div class="form-group">
                {{ form.action(class_='action', autofocus=True) }}
                {{ form.submit(class_='submit') }}
            </div>
        {% endif %}    
    </form>
    {% if not game.current_room.is_quiz() and game.current_room.max_errors <= 20 %}
    <p class="room-chances">Remaining chances: 
        {% if game.current_room.max_errors <= 3 %}
        <b style="color: red;">{{ game.current_room.max_errors }}</b>
        {% else %}
        <b>{{ game.current_room.max_errors }}</b>
        {% endif %}
    </p>
    {% endif %}
</div>

{% endblock %}

app/templates/game/gameover.html
{% extends "layout.html" %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='/css/game.css') }}">
{% endblock %}

{% block content %}
<div class="game-container">
    {% include 'game/_gameroom.html' %}

    <h2>Final Score: {{ game.calculated_score() }}</h2>
    <div class="play-again">
        <a href="{{ url_for('game.play', name=game.name) }}">Play Again?</a>
        <a href="{{ url_for('main.home') }}">Return to the game list</a>
    </div>
</div>

{% endblock %}

app/templates/game/mosquito.html
{% extends "layout.html" %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='/css/game.css') }}">
{% endblock %}


{% block content %}
{% endblock %}